language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
services:
  - mongodb
addons:
  apt:
    packages:
      - libsnappy-dev
env:
  global:
    # Doctr deploy key for NSLS-II/NSLS-II.github.io
    - secure: "dbjw3t57yRD8sIfeWnyIbUOxFI6upKHmhr5Kc4fqh8varqczi9LpnkrSABS/sdeb56rSwOnuTpgfwLB3qgqcodIepecAL9x7HDbNWejzQHHpKpE8ExsrBxKSLfX3CmU1veHZLk3UZV6ybhJCeut2f4kAsu14NlgmFc21u8C4AU/fQKGpoiWDTmzem1azck3903LE8zEpWRnTazhJuUd7H2KlsjEQd7bRFhKJHJmad7rXezWrfUrtFvNn3uKq6vYGQsqqvGGB3xIdjNxbJu2T8fqUkphc5VbLxQyGutK8uDviM7eq9wit6xY0tgDp4Av/eZjoYH7FwyQzqGMadn+QPnmW1izYFiOIcj7nw13S3Sfjs4FTkTD7pqdQTC1KMr72z86WdJBH/4FkRTFiXHRUbfRG5h+zZ7W7c8xI8SOfz4TQ1aakZ6JYt4Nxt+bQI9zh/5g3WEV2LRkLsBmM/nX+wGZpREE/s2+9LGMp9khdEReeklcXJ8W8pZb8iddMt4/zPS66Ej2nthJ9nd/QuurlOBh27GQFBGpSfmBe+XqDC9zHN0kWcUpPJ0mldvoWz/WtZw4VguuqTK+Kh9TqRYCbfXIHtCZMHaVsUVE7t1/HS6B/LlDwFVwxTvGrpl7Q0t3ZJi04vcitBUrWy2D7D7t5JXREhVlB999fMR7Gh4nXlKk="
    # Doctr deploy key for bluesky/bluesky.github.io
    - secure: "KoLab6lEqGJLK4aMSPysb9MTl6gEx3rpe0pGkIftmY1h0EO3jZ2ndVOEmopCvDbz9NtWGMm8blvQvQOMHh8psGXCgfSxrbESUT3D2VQm8tWC+UhxcFij9LdNFi0rKXLnfvkI4fwEp9yu1U+QkrLwYHMdLYPczDM+7HbXrgzFswAfiJyJZSZdHTzTuPPIEtn7set8V3a+qvS5WEwBgM1Y9fsoOfPlxI14BnUi8Pmq8QPNHI3L4pVzjBRTDbzrZzhv65UcJif1p3LL1oxv/3VT7TCh2cVu00MGg7gXyqsun+V3ELOAQ30p72Qd3YZqoa7p8s3lHlqpWSnVBbm8b1loVj/kWykLQuTQNk4+ZlgwaQ8WxyNtpdHIosIhM50xgjx3G3SsWJUgyQBcorWX+NAJ3EjTsddvjaoMb3EtvC7YsBYY6/qsIQjA16rxDfGgj9ibyS5pDFBfLK6jvQZKikFevME5/xFkMx67EJ5p3Z8C4sdoQgwIRlyyWtIFFO83ZSU/9snIy4niN8Gcx8o3hqUZ9f/EBE/1W4GvUSsTzZKBHWY0+Q+yiWUOnSzLfgAAGNhvXDHX6A1vqg0+5pnB122r5PGD0n7cUAt/vUXehjh/eDfnt6VMD4WLrSh5eyGx3YXggxaVrmwN/Cv8dZSIYheFI1Qry/17yhH6aRwZr9OSiRg="


install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - set -e
  - make -C docs html  # Build the documentation.
  # Pubish the documentation to GitHub Pages.
  - doctr deploy --built-docs docs/build/html --deploy-repo NSLS-II/NSLS-II.github.io intake-bluesky
  - doctr deploy --built-docs docs/build/html --deploy-repo bluesky/bluesky.github.io intake-bluesky
